language: generic

dist: bionic

matrix:
    include:
    - env: CXX=g++-9 CC=gcc-9
      addons:
        apt:
          packages:
            - g++-9
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - env: CXX=g++-8 CC=gcc-8
      addons:
        apt:
          packages:
            - g++-8
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
    - env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5

    - env: CXX=clang++-9 CC=clang-9
      addons:
        apt:
          packages:
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    - env: CXX=clang++-8 CC=clang-8
      addons:
        apt:
          packages:
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
    - env: CXX=clang++-7 CC=clang-7
      addons:
        apt:
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev


script:
    - if [[ "$CXX" == clang* ]]; then export CXXFLAGS="-stdlib=libc++"; fi
    - mkdir build && cd build
    - cmake -DINDICATORS_DEMO=ON -DINDICATORS_SAMPLES=ON ..
    - make
